---
version: "3.8"

services:
  deda-fork-server:
    build: .
    user: node:node
    environment:
      - CONFIG_ROOT=/home/node/config
      - UID=1000
      - GID=1000
    volumes:
      - /home/node/config:/home/node/config:rw
    ports:
      - 8080:8080
      - 4443:4443